### ISSUE TITLE
How to access local ads server?

### ISSUE THREAD

**Issue by acidos** [roccomuso/node-ads#8] opened 2018-07-23 20:53 UTC
I have successfully accessed remote ads target. But if I want to access target on the same machine(node app and target are same PC), then I get timeout.

```
var options = {
    host: "10.10.2.100",
    amsNetIdTarget: "10.10.2.100.1.1",
    amsNetIdSource: "10.10.2.100.1.1",
    amsPortTarget: 801
}

var myHandle = {
    symname: '.NoBeam',
    bytelength: ads.BOOL,  
    propname: 'value'      
}
var client = ads.connect(options, function() {
    this.read(myHandle, function(err, handle) {
        if (err) console.log(err)
        else console.log(handle.value)
        this.end()
    })
})

```
yields to `timeout` message printed only.
10.10.2.100 (and I also tried 127.0.0.1) added into static routing table.

Using TC2.

**Comment by acidos** [comment] 2018-07-24 13:41
C# client connecting to the same PLC from the same host just fine. Actually for local connection it's not necessary to put any access rule. But I put rule anyway, because without rule, your client is generating `ECONNRESET` exception. Once the rule is there, then `timeout`.

**Comment by roccomuso** [comment] 2018-07-24 14:17
Ok,
Can you try enabling debug? `DEBUG=node-ads node myclient.js`

**Comment by acidos** [comment] 2018-07-24 18:21
on Windows I did: `set DEBUG=node-ads`
then I run as usual `node index.js`. 
No change in output, perhaps it doesn't reach your code with debug.
```
c:\pkg>node index.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
```

My best guess would be usage of `amsNetIdSource`. I never seen such parameter in any client (C++, C#).

**Comment by acidos** [comment] 2018-07-24 19:59
I captured ADS traffic for your client and working client. Here is what I found.
- Apparently there is an ADS error in your client when ONLY reading. The error is Target port not found.
- However, the sequence of messages are very odd. Normally it should be like this:

```
1. (sender to target)request to create handle for symbol   
2. (target to sender)returned handle
3. (sender to target)ads read request with given handle
4. (target to sender)data provided
```

In your client I see the following sequence:

```
1. (sender to target)request to create handle for symbol   
2. (target to sender)returned handle
3. (sender to target)ADS Read/Write Response with error code target not found!?!?
end of messaging
```

It could be that the capturing program missed something, but I doubt.
If you are using AmsAdsViewer, I can provide with good/bad capture files.

**Comment by acidos** [comment] 2018-07-24 20:10
Routing in case of local connection is another mystery. Like I said, other clients doesn't need any routing in order to connect to PLC locally. However, your client requires explicit adding `127.0.0.1` into static routing table.

**Comment by roccomuso** [comment] 2018-07-26 08:44
I'll include @ovi1337 so maybe he could help debug since I don't have a TC2 right now.

**Comment by acidos** [comment] 2018-07-26 09:37
I have some feeling for the routing issue, that using C#, C++ client, which are using COM/DCOM communication probably directly, so they don't need routing. This theory is supporting also the fact, that I used rawcap utility to capture local traffic (127.0.0.1 and assigned IP), but couldn't see any packets while using C# client. However, I was able to see AMS packets from your client.

**Comment by ovi1337** [comment] 2018-07-26 09:37
@acidos the `amsNetIdTarget` and `amsNetIdSource` can't be the same, because this is a TCP/IP socket connection and you need a clear target and a destination. You can add a new route with another TargetId in the router configuration of your PLC like `10.10.2.100.1.1` and `10.10.2.100.1.2`.
Your node-ads project is basically an own simulated PLC.

**Comment by acidos** [comment] 2018-07-26 09:54
@ovi1337 it was not straight forward to add 2 routing entries with the same `127.0.0.1`. With few attempts I was able to add and read was successfull.

**Comment by ovi1337** [comment] 2018-07-26 20:20
And now it's working for you?

**Comment by acidos** [comment] 2018-07-26 20:47
Yes, although still not clear why C#/C+6 client producing AMS traffic with same sender/target ams net ID.

![image](https://user-images.githubusercontent.com/298480/43287509-8b942182-9125-11e8-8fef-ac8ee52755c5.png)

**Comment by sanderd17** [comment] 2018-07-30 09:13
@acidos, could you share your config?

* Did you use the connect on IP or hostname?
* How did you name your connections?

I'm also trying to add two entries, but can't seem to figure that one out.

**Comment by acidos** [comment] 2018-07-30 13:48
@sanderd17 

- I've used IP 127.0.0.1 for both entries.
- It appears to me bug in TC2 SM, since 2 entries are name sensitive. I named them differently, right now "first" and "second" naming works for me.

![image](https://user-images.githubusercontent.com/298480/43401194-c9e05c2a-940f-11e8-89d7-1fb4b205deb7.png)

Note the second entry comment, it says Sub route. The comment is not added by me.

**Comment by ChrisHanuta** [comment] 2018-08-28 19:15
If I understood correctly, it is on the router on the CE PLC. I found this:

TwinCAT AMS Router doesn't allow multiple TCP connections from the same host. So when you use two AdsLib instances on the same host to connect to the same TwinCAT router, you will see that TwinCAT will close the first TCP connection and only respond to the newest.
As ADS is transmitted over a TCP connection, there is no real time guarantee.
You can set up a second IPv4 on the PC and assign to this a ADS NET ID under Twincat. But you have to disable DHCP and enter all IP addresses by hand.

**Comment by acidos** [comment] 2018-09-11 19:37
Not sure if it's related to localhost restrictions, but even though I use `.end` in order to clean up connection, in event viewer I always see

    TCP/IP Connection: Socket to Peer Name: 127.0.0.1, Port: 17657 is connected, current socket will be closed!

after each connect->write->end cycle. Port number is different of course each time. Could it be that connection is not teardown properly?

**Comment by ChrisHanuta** [comment] 2018-09-12 09:01
The .end works asynchronously. I had a similar problem with node red implementation. You have to wait for the callback from .end before you start a new connection. In the Note Red implementation, I added a sleep of 1s. But I'm still surprised that it works locally at all, but I assume that the system manager is not running.

```
    node.on('close', function (done) {
      node.adsNotificationNodes = []
      node.systemNodes = []
      internalRestart(done)
    })

    function internalRestart(done) {
      internalSetConnectState(adsHelpers.connectState.DISCONNECTING)
      clearTimeout(conncetTimer)
      if (node.adsClient) {
        node.adsClient.end(function (){
          internalSetConnectState(adsHelpers.connectState.DISCONNECTED)
          delete (node.adsClient)
          var sleep = setInterval(function () {
            clearTimeout(sleep)
            done()
          },1000)
        })
      } else {
        internalSetConnectState(adsHelpers.connectState.DISCONNECTED)
        done()
      }
    }
```
This is an example from the implementation, done is called when the connection is down.

**Comment by ChrisHanuta** [comment] 2018-09-12 11:12
`client.end(function (){ resolve() })`

**Comment by acidos** [comment] 2018-09-13 08:50
I run my node client from different host, where there is no TC, with adding rule into static route, but the message

    TCP/IP Connection: Socket to Peer Name: <IP of remote client PC, where there is no TC>, Port: 41695 is connected, current socket will be closed!

So in the ADS capture I see `ADSIGRP_SYM_RELEASEHND` messages are there, but the info message clearly tells that TCP connection is not tear down properly. Basically it's not related to local/remote host use cases.

**Comment by ChrisHanuta** [comment] 2018-09-13 20:28
> So in the ADS capture I see ADSIGRP_SYM_RELEASEHND messages are there, but the info message clearly tells that TCP connection is not tear down properly. Basically it's not related to local/remote host use cases.

I discovered the following in end (). Maybe that's the problem:
```
var end = function (cb) {
  var ads = this
  ads.tcpClient.removeListener('data', ads.dataCallback)
  releaseSymHandles.call(ads, function () {
    releaseNotificationHandles.call(ads, function () {
      if (ads.tcpClient) {
        // ads.tcpClient.end(); // reijo removed
        ads.tcpClient.destroy() // reijo added
      }
      if (cb !== undefined) cb.call(ads)
    })
  })
}
```

may be end for tear down?
```
        ads.tcpClient.end(); // reijo removed
        // ads.tcpClient.destroy() // reijo added
```

**Comment by acidos** [comment] 2018-09-13 20:55
> may be end for tear down?

`.end` won't teardown connection, but will tidy up the stream only. Anyway, I went to `node_modules/node-ads/lib/ads.js` and opened `.end`. Also tried only with `.end`. Still get the `current socket will be closed` notification in Event Viewer.

**Comment by ChrisHanuta** [comment] 2018-09-14 08:14
I find this hint in the Beckhoff documentation:

[How to implement an ADS client](https://infosys.beckhoff.com/index.php?content=../content/1033/tcadscommon/html/tcadscommon_cookbookadsclient.htm)

> 6. Close ADS channel
> Always close ADS channel PortClose() – be aware to release handles before !

[Command Overview](https://infosys.beckhoff.com/index.php?content=../content/1033/tcadscommon/html/tcadscommon_cookbookadsclient.htm)

PortClose () is a function of the C ++ implementation. But I can not find a command for the ADS. I'm still not sure if the problem is in the socket or in the communication. The handles are released, I currently use to test an old CE PLC, I unfortunately have no monitor for this.

[Node.js v10.10.0 Documentation Net Socket](https://nodejs.org/docs/latest/api/net.html#net_class_net_socket)

I only see the function end() and destroy().

**Comment by acidos** [comment] 2018-09-14 09:16
> I unfortunately have no monitor for this

I don't use monitor for that, only Event Viewer

![image](https://user-images.githubusercontent.com/298480/45541483-921a0880-b80f-11e8-8eba-a0fbac33897e.png)

My setInterval is 5 min, so the events.

**Comment by ChrisHanuta** [comment] 2018-09-14 12:57
Which node version do you use?
`node --version`

**Comment by acidos** [comment] 2018-09-14 20:13
```
c:\pkg>node --version
v8.11.3

c:\pkg>npm --version
6.4.1

TC 2.11 (build 2249)
```

**Comment by acidos** [comment] 2018-09-15 10:11
So with `TCP/IP Verbindung` it's clear now. 
127.0.0.1 should have worked, with just special connection names.
[
![ads-routing](https://user-images.githubusercontent.com/298480/45585166-569b3f00-b8e0-11e8-9a6a-339801d3ec46.gif)
](url)

**Comment by ChrisHanuta** [comment] 2018-09-15 22:28
@roccomuso please close

**Closed** 2018-09-16 00:13 UTC
Labels: bug
